### ISSUE TITLE
hasn't copied the file.

### ISSUE THREAD

**Issue by Babak-mhy** [r00t-3xp10it/backdoorppt#3]
While it says everything is OK and file has been copied in .../output folder, but nothing is there!
Thanks.

**Comment by r00t-3xp10it** [comment]
<br />

**If backdoorppt runs without any errors until the finish...**
<br />

### Possible causes:
    1º - 'ZENITY' dependencie its not installed (questions to user are made using zenity)
    2º - 'PAYLOAD TO BE TRANSFORMED' was not inputed correctly (in zenity windows)
    3º - 'PAYLOAD TO BE TRANSFORMED' its not a windows binary payload.exe 
    4º - 'ResourceHacker.exe' installed by backdoorppt its to 32bits and you are using 64bits
    5º - The 'Ruby Interpreter' its not working proper and it cant not transform the file
    6º - The 'Ruby interpreter' version its not compatible with ruby command used by this tool
           "backdoorppt tool uses ruby 1.8.7 command syntax"

### Try using the 'BASH TRANSFORMATION' method insted
    1º - edit 'settings' file and change the follow line:

    BASH_TRANSFORMATION=NO
    change it to:
    BASH_TRANSFORMATION=YES

    2º - save 'settings' file and run backdoorppt again

<br />

### Final notes:
**1º - its better for me to see a screenshot of the tool working**
**to better understand whats happening in your distro**
<br />

**Comment by m4drob0t** [comment]
Same problem with me
os:-Ubuntu 16
![1](https://cloud.githubusercontent.com/assets/22110523/22617914/e24c6d90-eaf5-11e6-9f54-59a6c1bb1820.png)

**Comment by r00t-3xp10it** [comment]
thank you for this screenshot brother...

<br />

## backdoorppt error displays:
I can see that the error its on **WINE** (64bits) software or in the 
**ResorceHacker.exe** installed inside wine thats giving bugs...

Looking at terminal displays i can see "**wine**" execution errors..
`fixme:uxtheme:BufferedPaintUnit stub()`
So using a diferent spoof extension method **will not** resolve the problem
because it resides in a **compatibility** problem betwuin the two softwares..

<br />

## ResourceHacker and wine64:

    Also i've been reading about ResourceHacker software and it only
    exists one executable for the two archs (x64 or x86) so i dont
    belive that the problem its on resourcehacker...

So i belive thats a problem of **compatibility** betwuiin ResourceHacker.exe
and wine64 (**64 archs**) installation, iam not the owner of this softwares, so
i can not fix a problem that i dont understand (because in my 32bits its working)...

<br />

## Final notes:
I can write a new funtion to stop ResourceHacker.exe from
changing payload icons, but thats one of the main funtions of this tool..

**Comment by r00t-3xp10it** [comment]
## ResourceHacker.exe compatibility issue under wine64 archs

    ResourceHacker.exe its giving bugs working under wine64 archs, to bypass the use
    of ResourceHacker software change the follow option to YES before runing backdoorppt

### backdoorppt/settings file
![backdoorppt](http://1.1m.yt/75ESvJp.png)

### OR read this article about wine32 bits install
[backdoorppt step-by-step](http://sicksec.gomezmarin.es/)

### Or download the correction to the sourcecode (thanks to @4w4k3 bug report)
[4w4k3 sourcecode correction fix](https://github.com/r00t-3xp10it/backdoorppt)

**Comment by r00t-3xp10it** [comment]
Issue resolved:
Resource hacker under wine 64 bits bug-fixed ..
