### ISSUE TITLE
freezing the computer after running

### ISSUE THREAD

**Issue by ramadansanli** [r00t-3xp10it/backdoorppt#4]
hey, 
after i run the backdoorppt it is just freezing the computer it is totally stopped what is the problem?
thanx

**Comment by r00t-3xp10it** [comment]
i dont have any clue, because i dont even know what operative system you are using
but iam i little surprissed that this simple script 'thats nothing of mutch complicated'
in the sourcecode to produce this results..

so..are you sure that my script its the blame?

**Comment by ramadansanli** [comment]
not at all.. it is run in kali?

**Comment by r00t-3xp10it** [comment]
yap..
I have try it on **kali rolling**(my current distro) 32 bits arch
**Ubuntu**(team menber) and **Mint**(team menber) distros..

**Comment by ramadansanli** [comment]
so the matter and the solution?

**Comment by r00t-3xp10it** [comment]
well if you can record a **video tutorial** for me to **see** whats appening will be great,
because like i've said before **i never have seen this bug report before**, so i have no
clue whats appenning (please take a note that no one else have reported this bug)...

Normally i ask for a **screenshot** to **'see'** whats appening...
but in your case i belive that a **video tutorial** will be better, thanks...

**Comment by ramadansanli** [comment]
i think there is no need for that much information about that problem as soon as i run it, it is just freezing the computer totally not possible to restart the computer by using the resatat button option from desktop only hard restart physically from the turn on/off button to make computer available to use! make sense?

**Comment by r00t-3xp10it** [comment]
"make sense?" none...
I really dont understand why thats appenning in your distro, because my
code does not do anything to mutch complicated for that kind of bugs...

Try to use another tool writen by me in '**bash'**
to understand if the problem its on **'bash' syntax**...
[Morpheus TCP/IP Hijacking tool repository](https://github.com/r00t-3xp10it/morpheus)
